stages:
  - test
  - analyze

test_job:
  stage: test
  script:
    - echo "Запуск тестов Go..."
    - go test .
    - echo "Тесты выполнены успешно!"
  only:
    - main

analyze_job:
  stage: analyze
  script:
    - echo "Лёгкий анализ без зависимостей:"
    - echo "1. Проверка синтаксиса:"
    - find . -name '*.go' -exec gofmt -l {} \; | grep -v vendor/ || true
    - echo "2. Подсчёт строк кода:"
    - find . -name '*.go' | xargs wc -l
    - echo "3. Проверка на наличие TODO:"
    - grep -rn "TODO" . || true
    - echo "Анализ завершён!"
